name: 'Get cache dependencies'
description: 'An action to get cached dependencies for faster builds'
runs:
  using: 'composite'
  steps:
    - name: 'Restore cached dependencies'
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: 'Install dependencies if cache miss'
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash